assistant:
  name: "AI助手"
  description: "通用AI助手，可以回答问题和帮助用户"
  enabled: true
  memory:
    enable: true
    type: "chroma"
    url: "http://localhost:8000"
  tools:
    - "web_search"
    - "file_manager"
  knowledge_bases:
    - "general_knowledge"
    - "faq"
  config:
    max_tokens: 4000
    temperature: 0.7

coder:
  name: "编程助手"
  description: "专门帮助编程和代码相关任务的AI助手"
  enabled: true
  memory:
    enable: true
    type: "chroma"
    url: "http://localhost:8001"
  tools:
    - "code_analyzer"
    - "git_tools"
    - "file_manager"
  knowledge_bases:
    - "programming_docs"
    - "code_examples"
  config:
    max_tokens: 8000
    temperature: 0.3

researcher:
  name: "研究助手"
  description: "专门进行研究和信息收集的AI助手"
  enabled: false
  memory:
    enable: false
    type: "chroma"
    url: ""
  tools:
    - "web_search"
    - "academic_search"
  knowledge_bases:
    - "research_papers"
  config:
    max_tokens: 6000
    temperature: 0.5 