description: "代码示例库"
type: "file_system"
connection_info:
  base_path: "./data/code_examples"
  supported_extensions: [".py", ".js", ".java", ".cpp", ".md"]
metadata:
  last_updated: "2024-01-01"
  file_count: 2000 