general_knowledge:
  description: "通用知识库，包含常见问题和答案"
  type: "vector_db"
  enabled: true
  connection_info:
    host: "localhost"
    port: 6333
    collection_name: "general_knowledge"
    api_key: "${QDRANT_API_KEY}"
  metadata:
    last_updated: "2024-01-01"
    document_count: 10000
    embedding_model: "text-embedding-ada-002"

faq:
  description: "常见问题知识库"
  type: "document_db"
  enabled: true
  connection_info:
    database_path: "./data/faq.db"
    table_name: "faq_items"
  metadata:
    last_updated: "2024-01-01"
    document_count: 500

programming_docs:
  description: "编程文档和API参考"
  type: "elasticsearch"
  enabled: true
  connection_info:
    host: "localhost"
    port: 9200
    index: "programming_docs"
    username: "${ES_USERNAME}"
    password: "${ES_PASSWORD}"
  metadata:
    last_updated: "2024-01-01"
    document_count: 50000

code_examples:
  description: "代码示例库"
  type: "file_system"
  enabled: true
  connection_info:
    base_path: "./data/code_examples"
    supported_extensions: [".py", ".js", ".java", ".cpp", ".md"]
  metadata:
    last_updated: "2024-01-01"
    file_count: 2000

research_papers:
  description: "研究论文知识库"
  type: "vector_db"
  enabled: false
  connection_info:
    host: "localhost"
    port: 6334
    collection_name: "research_papers"
    api_key: "${QDRANT_API_KEY}"
  metadata:
    last_updated: "2024-01-01"
    document_count: 100000
    embedding_model: "text-embedding-ada-002" 